[build]
  functions = "functions/"

[[redirects]]
  from ="/api/login"
  to = ".netlify/functions/login"
  status = 200
  headers = {Content-Type = "application/json"}

[[redirects]]
  from ="/api/register"
  to = ".netlify/functions/register"
  status = 200
  headers = {Content-Type = "application/json"}

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search/:splat"

[[redirects]]
  from = "/api/album/all_album_image_links"
  to = "/.netlify/functions/album/all_album_image_links/:splat"
