[build]
  functions = "functions/"

[[redirects]]
  from ="/api/login"
  to = "/.netlify/functions/login"
  status = 200

  [[redirects]]
  from ="/api/logout"
  to = "/.netlify/functions/logout"
  status = 200

[[redirects]]
  from ="/api/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from ="/api/update_favorites"
  to = "/.netlify/functions/updateFavorites"
  status = 200

[[redirects]]
  from ="/api/saved_favorites"
  to = "/.netlify/functions/savedFavorites"
  status = 200

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search/:splat"

[[redirects]]
  from = "/api/album/all_album_image_links"
  to = "/.netlify/functions/album/all_album_image_links/:splat"
